disabledCache = false
noCache = ['/robots.txt', '/sitemap.txt']

[paths]

'/' = '/routes/Index.js'
'/dialectology' = '/routes/Dialectology.js'
'/baltistics' = '/routes/Baltistics.js'

[redirects]

'/favicon.ico' = '/assets/favicon.png'

[api]

'/api/navigation' = '/api/navigation.js'
'/api/page' = '/api/page.js'
'/api/page/v2' = '/api/page.v2.js'

[languages]

default = 'lt'
lt = 'lt'
en = 'en'
