[paths]

'/' = '/routes/Index.js'
'/dialectology' = '/routes/Dialectology.js'

[redirects]

'/favicon.ico' = '/assets/favicon.png'

[api]

'/api/example' = '/api/example.js'
'/api/navigation' = '/api/navigation.js'
