import type {GROUPS} from 'back/api/verbGroups.ts'

const CONJUGATED_KEYS = [
  'būti-yra-buvo',
  `bū́ti-yra\u0300-bùvo`,
  'būti-būna-buvo',
  'bū́ti-bū́na-bùvo',
  'lėkti-lekia-lėkė',
  `lė\u0303kti-le\u0303kia-lė\u0303kė`,
  `nešti-neša-nešė`,
  `ne\u0300šti-ne\u0303ša-ne\u0303šė`,
  `šviesti-šviečia-švietė`,
  `švie\u0303sti-švie\u0303čia-švie\u0303tė`,
  `tikėti-tiki-tikėjo`,
  `tikė\u0301ti-ti\u0300ki-tikė\u0301jo`,
  `mylė\u0301ti-my\u0301li-mylė\u0301jo`,
  `girdėti-girdi-girdėjo`,
  `girdė\u0301ti-gir\u0303di-girdė\u0301jo`,
  `siūti-siuva-siuvo`,
  `siū\u0301ti-siū\u0303na-siu\u0300vo`,
  `vyti-veja-vijo`,
  `vy\u0301ti-ve\u0303ja-vi\u0300jo`,
  `myžti-myža-myžo`,
  `slysti-slysta-slydo`,
] as const

export const CONJUGATED: Record<
  (typeof CONJUGATED_KEYS)[number],
  Record<keyof typeof GROUPS, object>
> = {
  ['būti-yra-buvo']: {
    presInd: {
      sg1: 'esu',
      sg2: 'esi',
      sg3: 'yra',
      pl1: 'esame',
      pl2: 'esate',
      pl3: 'yra',
    },
    pastInd: {
      sg1: 'buvau',
      sg2: 'buvai',
      sg3: 'buvo',
      pl1: 'buvome',
      pl2: 'buvote',
      pl3: 'buvo',
    },
    pastFreqInd: {
      sg1: 'būdavau',
      sg2: 'būdavai',
      sg3: 'būdavo',
      pl1: 'būdavome',
      pl2: 'būdavote',
      pl3: 'būdavo',
    },
    futInd: {
      sg1: 'būsiu',
      sg2: 'būsi',
      sg3: 'bus',
      pl1: 'būsime',
      pl2: 'būsite',
      pl3: 'bus',
    },
  },
  ['bū́ti-yrà-bùvo']: {
    presInd: {
      sg1: 'esù',
      sg2: 'esì',
      sg3: 'yrà',
      pl1: 'ẽsame',
      pl2: 'ẽsate',
      pl3: 'yrà',
    },
    pastInd: {
      sg1: 'buvaũ',
      sg2: 'buvaĩ',
      sg3: 'bùvo',
      pl1: 'bùvome',
      pl2: 'bùvote',
      pl3: 'bùvo',
    },
    pastFreqInd: {
      sg1: 'bū́davau',
      sg2: 'bū́davai',
      sg3: 'bū́davo',
      pl1: 'bū́davome',
      pl2: 'bū́davote',
      pl3: 'bū́davo',
    },
    futInd: {
      sg1: 'bū́siu',
      sg2: 'bū́si',
      sg3: 'bùs',
      pl1: 'bū́sime',
      pl2: 'bū́site',
      pl3: 'bùs',
    },
  },
  ['būti-būna-buvo']: {
    presInd: {
      sg1: 'būnu',
      sg2: 'būni',
      sg3: 'būna',
      pl1: 'būname',
      pl2: 'būnate',
      pl3: 'būna',
    },
    pastInd: {
      sg1: 'buvau',
      sg2: 'buvai',
      sg3: 'buvo',
      pl1: 'buvome',
      pl2: 'buvote',
      pl3: 'buvo',
    },
    pastFreqInd: {
      sg1: 'būdavau',
      sg2: 'būdavai',
      sg3: 'būdavo',
      pl1: 'būdavome',
      pl2: 'būdavote',
      pl3: 'būdavo',
    },
    futInd: {
      sg1: 'būsiu',
      sg2: 'būsi',
      sg3: 'bus',
      pl1: 'būsime',
      pl2: 'būsite',
      pl3: 'bus',
    },
  },
  ['bū́ti-bū́na-bùvo']: {
    presInd: {
      sg1: 'bū́nu',
      sg2: 'bū́ni',
      sg3: 'bū́na',
      pl1: 'bū́name',
      pl2: 'bū́nate',
      pl3: 'bū́na',
    },
    pastInd: {
      sg1: 'buvaũ',
      sg2: 'buvaĩ',
      sg3: 'bùvo',
      pl1: 'bùvome',
      pl2: 'bùvote',
      pl3: 'bùvo',
    },
    pastFreqInd: {
      sg1: 'bū́davau',
      sg2: 'bū́davai',
      sg3: 'bū́davo',
      pl1: 'bū́davome',
      pl2: 'bū́davote',
      pl3: 'bū́davo',
    },
    futInd: {
      sg1: 'bū́siu',
      sg2: 'bū́si',
      sg3: 'bùs',
      pl1: 'bū́sime',
      pl2: 'bū́site',
      pl3: 'bùs',
    },
  },
  ['lėkti-lekia-lėkė']: {
    presInd: {
      sg1: 'lekiu',
      sg2: 'leki',
      sg3: 'lekia',
      pl1: 'lekiame',
      pl2: 'lekiate',
      pl3: 'lekia',
    },
    pastInd: {
      sg1: 'lėkiau',
      sg2: 'lėkei',
      sg3: 'lėkė',
      pl1: 'lėkėme',
      pl2: 'lėkėte',
      pl3: 'lėkė',
    },
    pastFreqInd: {
      sg1: 'lėkdavau',
      sg2: 'lėkdavai',
      sg3: 'lėkdavo',
      pl1: 'lėkdavome',
      pl2: 'lėkdavote',
      pl3: 'lėkdavo',
    },
    futInd: {
      sg1: 'lėksiu',
      sg2: 'lėksi',
      sg3: 'lėks',
      pl1: 'lėksime',
      pl2: 'lėksite',
      pl3: 'lėks',
    },
  },
  ['lė̃kti-lẽkia-lė̃kė']: {
    presInd: {
      sg1: 'lekiù',
      sg2: 'lekì',
      sg3: 'lẽkia',
      pl1: 'lẽkiame',
      pl2: 'lẽkiate',
      pl3: 'lẽkia',
    },
    pastInd: {
      sg1: 'lėkiaũ',
      sg2: 'lėkeĩ',
      sg3: 'lė̃kė',
      pl1: 'lė̃kėme',
      pl2: 'lė̃kėte',
      pl3: 'lė̃kė',
    },
    pastFreqInd: {
      sg1: 'lė̃kdavau',
      sg2: 'lė̃kdavai',
      sg3: 'lė̃kdavo',
      pl1: 'lė̃kdavome',
      pl2: 'lė̃kdavote',
      pl3: 'lė̃kdavo',
    },
    futInd: {
      sg1: 'lė̃ksiu',
      sg2: 'lė̃ksi',
      sg3: 'lė̃ks',
      pl1: 'lė̃ksime',
      pl2: 'lė̃ksite',
      pl3: 'lė̃ks',
    },
  },
  ['nešti-neša-nešė']: {
    presInd: {
      sg1: 'nešu',
      sg2: 'neši',
      sg3: 'neša',
      pl1: 'nešame',
      pl2: 'nešate',
      pl3: 'neša',
    },
    pastInd: {
      sg1: 'nešiau',
      sg2: 'nešei',
      sg3: 'nešė',
      pl1: 'nešėme',
      pl2: 'nešėte',
      pl3: 'nešė',
    },
    pastFreqInd: {
      sg1: 'nešdavau',
      sg2: 'nešdavai',
      sg3: 'nešdavo',
      pl1: 'nešdavome',
      pl2: 'nešdavote',
      pl3: 'nešdavo',
    },
    futInd: {
      sg1: 'nešiu',
      sg2: 'neši',
      sg3: 'neš',
      pl1: 'nešime',
      pl2: 'nešite',
      pl3: 'neš',
    },
  },
  ['nèšti-nẽša-nẽšė']: {
    presInd: {
      sg1: 'nešù',
      sg2: 'nešì',
      sg3: 'nẽša',
      pl1: 'nẽšame',
      pl2: 'nẽšate',
      pl3: 'nẽša',
    },
    pastInd: {
      sg1: 'nešiaũ',
      sg2: 'nešeĩ',
      sg3: 'nẽšė',
      pl1: 'nẽšėme',
      pl2: 'nẽšėte',
      pl3: 'nẽšė',
    },
    pastFreqInd: {
      sg1: 'nèšdavau',
      sg2: 'nèšdavai',
      sg3: 'nèšdavo',
      pl1: 'nèšdavome',
      pl2: 'nèšdavote',
      pl3: 'nèšdavo',
    },
    futInd: {
      sg1: 'nèšiu',
      sg2: 'nèši',
      sg3: 'nèš',
      pl1: 'nèšime',
      pl2: 'nèšite',
      pl3: 'nèš',
    },
  },
  ['šviesti-šviečia-švietė']: {
    presInd: {
      sg1: 'šviečiu',
      sg2: 'švieti',
      sg3: 'šviečia',
      pl1: 'šviečiame',
      pl2: 'šviečiate',
      pl3: 'šviečia',
    },
    pastInd: {
      sg1: 'šviečiau',
      sg2: 'švietei',
      sg3: 'švietė',
      pl1: 'švietėme',
      pl2: 'švietėte',
      pl3: 'švietė',
    },
    pastFreqInd: {
      sg1: 'šviesdavau',
      sg2: 'šviesdavai',
      sg3: 'šviesdavo',
      pl1: 'šviesdavome',
      pl2: 'šviesdavote',
      pl3: 'šviesdavo',
    },
    futInd: {
      sg1: 'šviesiu',
      sg2: 'šviesi',
      sg3: 'švies',
      pl1: 'šviesime',
      pl2: 'šviesite',
      pl3: 'švies',
    },
  },
  ['šviẽsti-šviẽčia-šviẽtė']: {
    presInd: {
      sg1: 'šviečiù',
      sg2: 'švietì',
      sg3: 'šviẽčia',
      pl1: 'šviẽčiame',
      pl2: 'šviẽčiate',
      pl3: 'šviẽčia',
    },
    pastInd: {
      sg1: 'šviečiaũ',
      sg2: 'švieteĩ',
      sg3: 'šviẽtė',
      pl1: 'šviẽtėme',
      pl2: 'šviẽtėte',
      pl3: 'šviẽtė',
    },
    pastFreqInd: {
      sg1: 'šviẽsdavau',
      sg2: 'šviẽsdavai',
      sg3: 'šviẽsdavo',
      pl1: 'šviẽsdavome',
      pl2: 'šviẽsdavote',
      pl3: 'šviẽsdavo',
    },
    futInd: {
      sg1: 'šviẽsiu',
      sg2: 'šviẽsi',
      sg3: 'šviẽs',
      pl1: 'šviẽsime',
      pl2: 'šviẽsite',
      pl3: 'šviẽs',
    },
  },
  ['tikėti-tiki-tikėjo']: {
    presInd: {
      sg1: 'tikiu',
      sg2: 'tiki',
      sg3: 'tiki',
      pl1: 'tikime',
      pl2: 'tikite',
      pl3: 'tiki',
    },
    pastInd: {
      sg1: 'tikėjau',
      sg2: 'tikėjai',
      sg3: 'tikėjo',
      pl1: 'tikėjome',
      pl2: 'tikėjote',
      pl3: 'tikėjo',
    },
    pastFreqInd: {
      sg1: 'tikėdavau',
      sg2: 'tikėdavai',
      sg3: 'tikėdavo',
      pl1: 'tikėdavome',
      pl2: 'tikėdavote',
      pl3: 'tikėdavo',
    },
    futInd: {
      sg1: 'tikėsiu',
      sg2: 'tikėsi',
      sg3: 'tikės',
      pl1: 'tikėsime',
      pl2: 'tikėsite',
      pl3: 'tikės',
    },
  },
  ['tikė́ti-tìki-tikė́jo']: {
    presInd: {
      sg1: 'tikiù',
      sg2: 'tikì',
      sg3: 'tìki',
      pl1: 'tìkime',
      pl2: 'tìkite',
      pl3: 'tìki',
    },
    pastInd: {
      sg1: 'tikė́jau',
      sg2: 'tikė́jai',
      sg3: 'tikė́jo',
      pl1: 'tikė́jome',
      pl2: 'tikė́jote',
      pl3: 'tikė́jo',
    },
    pastFreqInd: {
      sg1: 'tikė́davau',
      sg2: 'tikė́davai',
      sg3: 'tikė́davo',
      pl1: 'tikė́davome',
      pl2: 'tikė́davote',
      pl3: 'tikė́davo',
    },
    futInd: {
      sg1: 'tikė́siu',
      sg2: 'tikė́si',
      sg3: 'tikė̃s',
      pl1: 'tikė́sime',
      pl2: 'tikė́site',
      pl3: 'tikė̃s',
    },
  },
  ['mylė́ti-mýli-mylė́jo']: {
    presInd: {
      sg1: 'mýliu',
      sg2: 'mýli',
      sg3: 'mýli',
      pl1: 'mýlime',
      pl2: 'mýlite',
      pl3: 'mýli',
    },
    pastInd: {
      sg1: 'mylė́jau',
      sg2: 'mylė́jai',
      sg3: 'mylė́jo',
      pl1: 'mylė́jome',
      pl2: 'mylė́jote',
      pl3: 'mylė́jo',
    },
    pastFreqInd: {
      sg1: 'mylė́davau',
      sg2: 'mylė́davai',
      sg3: 'mylė́davo',
      pl1: 'mylė́davome',
      pl2: 'mylė́davote',
      pl3: 'mylė́davo',
    },
    futInd: {
      sg1: 'mylė́siu',
      sg2: 'mylė́si',
      sg3: 'mylė̃s',
      pl1: 'mylė́sime',
      pl2: 'mylė́site',
      pl3: 'mylė̃s',
    },
  },
  ['girdėti-girdi-girdėjo']: {
    presInd: {
      sg1: 'girdžiu',
      sg2: 'girdi',
      sg3: 'girdi',
      pl1: 'girdime',
      pl2: 'girdite',
      pl3: 'girdi',
    },
    pastInd: {
      sg1: 'girdėjau',
      sg2: 'girdėjai',
      sg3: 'girdėjo',
      pl1: 'girdėjome',
      pl2: 'girdėjote',
      pl3: 'girdėjo',
    },
    pastFreqInd: {
      sg1: 'girdėdavau',
      sg2: 'girdėdavai',
      sg3: 'girdėdavo',
      pl1: 'girdėdavome',
      pl2: 'girdėdavote',
      pl3: 'girdėdavo',
    },
    futInd: {
      sg1: 'girdėsiu',
      sg2: 'girdėsi',
      sg3: 'girdės',
      pl1: 'girdėsime',
      pl2: 'girdėsite',
      pl3: 'girdės',
    },
  },
  ['girdė́ti-gir̃di-girdė́jo']: {
    presInd: {
      sg1: 'girdžiù',
      sg2: 'girdì',
      sg3: 'gir̃di',
      pl1: 'gir̃dime',
      pl2: 'gir̃dite',
      pl3: 'gir̃di',
    },
    pastInd: {
      sg1: 'girdė́jau',
      sg2: 'girdė́jai',
      sg3: 'girdė́jo',
      pl1: 'girdė́jome',
      pl2: 'girdė́jote',
      pl3: 'girdė́jo',
    },
    pastFreqInd: {
      sg1: 'girdė́davau',
      sg2: 'girdė́davai',
      sg3: 'girdė́davo',
      pl1: 'girdė́davome',
      pl2: 'girdė́davote',
      pl3: 'girdė́davo',
    },
    futInd: {
      sg1: 'girdė́siu',
      sg2: 'girdė́si',
      sg3: 'girdė̃s',
      pl1: 'girdė́sime',
      pl2: 'girdė́site',
      pl3: 'girdė̃s',
    },
  },
  ['siūti-siuva-siuvo']: {
    presInd: {
      sg1: 'siuvu',
      sg2: 'siuvi',
      sg3: 'siuva',
      pl1: 'siuvame',
      pl2: 'siuvate',
      pl3: 'siuva',
    },
    pastInd: {
      sg1: 'siuvau',
      sg2: 'siuvai',
      sg3: 'siuvo',
      pl1: 'siuvome',
      pl2: 'siuvote',
      pl3: 'siuvo',
    },
    pastFreqInd: {
      sg1: 'siūdavau',
      sg2: 'siūdavai',
      sg3: 'siūdavo',
      pl1: 'siūdavome',
      pl2: 'siūdavote',
      pl3: 'siūdavo',
    },
    futInd: {
      sg1: 'siūsiu',
      sg2: 'siūsi',
      sg3: 'siūs',
      pl1: 'siūsime',
      pl2: 'siūsite',
      pl3: 'siūs',
    },
  },
  ['siū́ti-siū̃na-siùvo']: {
    presInd: {
      sg1: 'siūnù',
      sg2: 'siūnì',
      sg3: 'siū̃na',
      pl1: 'siū̃name',
      pl2: 'siū̃nate',
      pl3: 'siū̃na',
    },
    pastInd: {
      sg1: 'siuvaũ',
      sg2: 'siuvaĩ',
      sg3: 'siùvo',
      pl1: 'siùvome',
      pl2: 'siùvote',
      pl3: 'siùvo',
    },
    pastFreqInd: {
      sg1: 'siū́davau',
      sg2: 'siū́davai',
      sg3: 'siū́davo',
      pl1: 'siū́davome',
      pl2: 'siū́davote',
      pl3: 'siū́davo',
    },
    futInd: {
      sg1: 'siū́siu',
      sg2: 'siū́si',
      sg3: `siū\u0303s`,
      pl1: 'siū́sime',
      pl2: 'siū́site',
      pl3: `siū\u0303s`,
    },
  },
  ['vyti-veja-vijo']: {
    presInd: {
      sg1: 'veju',
      sg2: 'veji',
      sg3: 'veja',
      pl1: 'vejame',
      pl2: 'vejate',
      pl3: 'veja',
    },
    pastInd: {
      sg1: 'vijau',
      sg2: 'vijai',
      sg3: 'vijo',
      pl1: 'vijome',
      pl2: 'vijote',
      pl3: 'vijo',
    },
    pastFreqInd: {
      sg1: 'vydavau',
      sg2: 'vydavai',
      sg3: 'vydavo',
      pl1: 'vydavome',
      pl2: 'vydavote',
      pl3: 'vydavo',
    },
    futInd: {
      sg1: 'vysiu',
      sg2: 'vysi',
      sg3: 'vys',
      pl1: 'vysime',
      pl2: 'vysite',
      pl3: 'vys',
    },
  },
  ['výti-vẽja-vìjo']: {
    presInd: {
      sg1: 'vejù',
      sg2: 'vejì',
      sg3: 'vẽja',
      pl1: 'vẽjame',
      pl2: 'vẽjate',
      pl3: 'vẽja',
    },
    pastInd: {
      sg1: 'vijaũ',
      sg2: 'vijaĩ',
      sg3: 'vìjo',
      pl1: 'vìjome',
      pl2: 'vìjote',
      pl3: 'vìjo',
    },
    pastFreqInd: {
      sg1: 'výdavau',
      sg2: 'výdavai',
      sg3: 'výdavo',
      pl1: 'výdavome',
      pl2: 'výdavote',
      pl3: 'výdavo',
    },
    futInd: {
      sg1: 'výsiu',
      sg2: 'výsi',
      sg3: `vy\u0303s`,
      pl1: 'výsime',
      pl2: 'výsite',
      pl3: `vy\u0303s`,
    },
  },
  ['myžti-myža-myžo']: {
    presInd: {
      sg1: 'myžu',
      sg2: 'myži',
      sg3: 'myža',
      pl1: 'myžame',
      pl2: 'myžate',
      pl3: 'myža',
    },
    pastInd: {
      sg1: 'myžau',
      sg2: 'myžai',
      sg3: 'myžo',
      pl1: 'myžome',
      pl2: 'myžote',
      pl3: 'myžo',
    },
    pastFreqInd: {
      sg1: 'myždavau',
      sg2: 'myždavai',
      sg3: 'myždavo',
      pl1: 'myždavome',
      pl2: 'myždavote',
      pl3: 'myždavo',
    },
    futInd: {
      sg1: 'myšiu',
      sg2: 'myši',
      sg3: 'myš',
      pl1: 'myšime',
      pl2: 'myšite',
      pl3: 'myš',
    },
  },
  ['slysti-slysta-slydo']: {
    presInd: {
      sg1: 'slystu',
      sg2: 'slysti',
      sg3: 'slysta',
      pl1: 'slystame',
      pl2: 'slystate',
      pl3: 'slysta',
    },
    pastInd: {
      sg1: 'slydau',
      sg2: 'slydai',
      sg3: 'slydo',
      pl1: 'slydome',
      pl2: 'slydote',
      pl3: 'slydo',
    },
    pastFreqInd: {
      sg1: 'slysdavau',
      sg2: 'slysdavai',
      sg3: 'slysdavo',
      pl1: 'slysdavome',
      pl2: 'slysdavote',
      pl3: 'slysdavo',
    },
    futInd: {
      sg1: 'slysiu',
      sg2: 'slysi',
      sg3: 'slys',
      pl1: 'slysime',
      pl2: 'slysite',
      pl3: 'slys',
    },
  },
}
